version: '3.4'

services:
  medprwebapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__Default=Server=host.docker.internal,1433; Database=ITA-Medpr; User=sa; Password=8yQD!yya
      - ConnectionStrings__Identity=Server=host.docker.internal,1433; Database=ITA-Medpr-Identity; User=sa; Password=8yQD!yya
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro