services:
  medprwebapi:
    container_name: webAPI
    image: ${DOCKER_REGISTRY-}medprwebapi
    build:
      context: .
      dockerfile: MedprWebAPI/Dockerfile
    ports:
      - "7295:443"
    depends_on: [sqlserver]

  sqlserver:
    container_name: sql_server
    image: sql-server-image
    build:
      context: .
      dockerfile: Dockerfile-sql
    environment:
      - COMPOSE_PROJECT_NAME=medpr
      - SA_PASSWORD=8yQD!yya
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

  medprangular:
    container_name: angular
    image: medprangular
    build: 
      context: ./Angular/medpr-angular/
      dockerfile: Dockerfile
    command: sh -c "npm start"
    working_dir: /home/node/app
    ports:
      - 4200:4200
    volumes:
      - ./Angular/medpr-angular:/home/node/app
      - node_modules:/home/node/app/node_modules
    depends_on: [sqlserver, medprwebapi]

volumes:
  node_modules: