name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Build and push
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: latest
          registry: medpr
          dockerfile: github.com/LexKutler/Medpr/MedprWebAPI
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
            
